### ISSUE TITLE
Add license.txt

### ISSUE THREAD

**Issue by duanestorey** [WordPress/secure-custom-fields#1]
The GPL requires the original copyright of the code stays in place, even after a fork.  Where does this exist?  You've clearly taken the ACF Pro plugin and mostly checked it in as-is, after stripping the licensing etc, which is odd considering Automattic is suing a company for basically doing this same thing.  It also violates several of the WordPress plugin guidelines, but who cares about those, right?

**Comment by freddurst1805** [comment]
At first I saw the intention of SCF as a good opportunity for the community to have a fully functionnal ACF Clone with free pro features developed by the community, but since the SCF has been forked it seems they did nothing in the right direction.
They care only about their own business.

**Comment by kraftbj** [comment]
Thanks @duanestorey. You're right that we need to add a license.txt. The original version that this is being forked from did not have that as best as I can tell. This was pushed up to bring the work into a public repo, even if not 100% ready to go.

**Comment by duanestorey** [comment]
It's not just that it needs some indication that it's GPL, my understanding is that it needs to credit the original copyright holders (WPE and the original author as well) to be GPL compliant. 

You should also be aware that ACF is a registered trademark of WP Engine, and the code you are modifying is littered with references to that:

https://tsdr.uspto.gov/#caseNumber=98321135&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch

**Comment by kraftbj** [comment]
> It's not just that it needs some indication that it's GPL, my understanding is that it needs to credit the original copyright holders (WPE and the original author as well) to be GPL compliant.

Sorry, yes, that's what I meant. The WordPress license.txt is what I meant as an example ( https://github.com/WordPress/WordPress/blob/master/license.txt ) in that it references the previous work in addition to include the GPL license itself.
