### ISSUE TITLE
acf.php -> secure-custom-fields.php

### ISSUE THREAD

**Issue by robertdevore** [WordPress/secure-custom-fields#7]
If you're using this plugin as an opportunity to replace ACF and also replace the original SCF in the wp.org repo, why wouldn't you just start with a fresh file name?

I mean, if the goal is to actually maintain this version of a fork, why wouldn't you want to remove all instances of ACF both in filenames and in content?

**Comment by j-hoffmann** [comment]
Sadly the plugin slug and filename have to stay for tecnical reasons. 

Changing either one of the two could potentially break a lot of other plugins / themes when testing whether ACF / SCF is active. One way to test if the plugin is active would be `is_plugin_active( 'advanced-custom-fields/acf.php' )`.

Changing the slug would prevent all websites currently using the plugin from updating.

Probably there are plenty more examples where changing the names would lead to problems, but I don't think it is necessary to list them all.

**Comment by robertdevore** [comment]
That's if this plugin is what's going to be uploaded to www.wordpress.org/plugins/advanced-custom-fields/

But this looks to be what's being added to www.wordpress.org/plugins/secure-custom-fields/

Or maybe I'm just confused? 🤔

**Comment by petertwise** [comment]
Seems like this issue would be irrelevant if you address #5 first.

**Comment by robertdevore** [comment]
@petertwise Oh, for sure.

But on the off chance they're not interested in ethical dilemmas, they can at least address this file based one 😎

**Comment by j-hoffmann** [comment]
> Or maybe I'm just confused? 🤔

Well there was definately some confusion on my part, I hadn't realized that we now have two Plugins with the exact same name "Secure Custom Fields" in the wp.org plugin repository. Hence I also hadn't realized that this github repository isn't for the plugin entry seized from WP Engine, but for the new plugin entry instead.

**Comment by robertdevore** [comment]
Same, it's all so confusing. Maybe @kraftbj can provide some insight on the issue 👀

**Comment by fusionaddict** [comment]
> Sadly the plugin slug and filename have to stay for tecnical reasons.
> 
> Changing either one of the two could potentially break a lot of other plugins / themes when testing whether ACF / SCF is active. One way to test if the plugin is active would be `is_plugin_active( 'advanced-custom-fields/acf.php' )`.
> 
> Changing the slug would prevent all websites currently using the plugin from updating.
> 
> Probably there are plenty more examples where changing the names would lead to problems, but I don't think it is necessary to list them all.

So what you're saying is, "Because Automattic decided to use an actual, by-definition _supply-chain attack_ to distribute this hastily-cobbled-together knockoff, they can't fix it without breaking everyone's sites."

**Comment by fusionaddict** [comment]
> If you're using this plugin as an opportunity to replace ACF and also replace the original SCF in the wp.org repo, why wouldn't you just start with a fresh file name?

Because then Matt wouldn't be able to use a supply-chain attack to forcibly distribute it.

**Comment by j-hoffmann** [comment]
> So what you're saying is, "Because Automattic decided to use an actual, by-definition _supply-chain attack_ to distribute this hastily-cobbled-together knockoff, they can't fix it without breaking everyone's sites."

@fusionaddict As it turns out, there are now two plugins with the same name in the wp.org repo. One ist the original non Pro version seized from WP Engine and the other one seems to be a new listing in the repository. This new plugin version also comes with most of the code taken from the Advanced Custom Fields Pro version. This github repository seems to feed to the new pugin listing which currently only has a few hundred installs (but growing). It comes with a new plugin slug "secure-custom-fields", so what I said above doesn't seem to apply here.

**Comment by pixelmultiplo** [comment]
Because it's not a fork, it's a stolen copy.

**Comment by scrobbleme** [comment]
+1 for at taking the chance and create a "new" plugin out of it. ACF also has a lot of legacy code. This is a chance to get rid of some technical debts...

There is no reason to maintain "compatibility" as long as possible. If WP itself has this as "core" plugin, developers will eventually adapt it anyway.

(to be clear, I didn't like the way everything worked out and definitely not how Automattic acted here)

**Comment by kraftbj** [comment]
@robertdevore That's a good point. In #11, the main plugin file is renamed with the original `acf.php` providing a way for sites already using this plugin to come along for the ride or, worst case, load the new main file while WP still includes the original plugin file.
